export const DISPLAY_ALERT = "SHOW_ALERT";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER ";

export const UPDATE_USER_BEGIN = "LOGIN_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const UPDATE_USER_ERROR = "LOGIN_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

//Users 

export const GET_USERS_BEGIN = "CREATE_USERS_BEGIN";
export const GET_USERS_SUCCESS = "CREATE_USERS_SUCCESS";

//Projects

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const GET_PROJECTS_BEGIN = "GET_PROJECTS_BEGIN";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";

export const SET_EDIT_PROJECT = "SET_EDIT_PROJECT";
export const SET_GET_PROJECTS = "SET_GET_PROJECTS";

export const DELETE_PROJECT_BEGIN = "DELETE_PROJECT_BEGIN";

export const EDIT_PROJECT_BEGIN = "EDIT_PROJECT_BEGIN";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";

export const SET_IS_PROJECT = "SET_IS_PROJECT";
export const SET_IS_FEATURE = "SET_IS_FEATURE";

export const CREATE_FEATURE_BEGIN = "CREATE_FEATURE_BEGIN";
export const CREATE_FEATURE_SUCCESS = "CREATE_FEATURE_SUCCESS";
export const CREATE_FEATURE_ERROR = "CREATE_FEATURE_ERROR";

export const GET_FEATURES_BEGIN = "GET_FEATURES_BEGIN";
export const GET_FEATURES_SUCCESS = "GET_FEATURES_SUCCESS";

export const SET_EDIT_FEATURE = "SET_EDIT_FEATURE";

export const DELETE_FEATURE_BEGIN = "DELETE_FEATURE_BEGIN";

export const EDIT_FEATURE_BEGIN = "EDIT_FEATURE_BEGIN";
export const EDIT_FEATURE_SUCCESS = "EDIT_FEATURE_SUCCESS";
export const EDIT_FEATURE_ERROR = "EDIT_FEATURE_ERROR";

export const CREATE_CREDIT_TRANSACTION_BEGIN = "CREATE_CREDIT_TRANSACTION_BEGIN";
export const CREATE_CREDIT_TRANSACTION_SUCCESS = "CREATE_CREDIT_TRANSACTION_SUCCESS";
export const CREATE_CREDIT_TRANSACTION_ERROR = "CREATE_CREDIT_TRANSACTION_ERROR";


export const CREATE_DEBIT_TRANSACTION_BEGIN = "CREATE_DEBIT_TRANSACTION_BEGIN";
export const CREATE_DEBIT_TRANSACTION_SUCCESS = "CREATE_DEBIT_TRANSACTION_SUCCESS";
export const CREATE_DEBIT_TRANSACTION_ERROR = "CREATE_DEBIT_TRANSACTION_ERROR";

export const SET_EDIT_DEBIT_TRANSACTION = "SET_EDIT_DEBIT_TRANSACTION";


export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_IMAGE_BEGIN = "CREATE_IMAGE_BEGIN";
export const CREATE_IMAGE_SUCCESS = "CREATE_IMAGE_SUCCESS";
export const CREATE_IMAGE_ERROR = "CREATE_IMAGE_ERROR";


 export const GET_IMAGES_BEGIN = "GET_IMAGES_BEGIN";
 export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
